--[[
    CooldownCompanion - Core/Defaults.lua: Profile schema and override sections registry
]]

local ADDON_NAME, ST = ...

-- Default database structure
local defaults = {
    profile = {
        minimap = {
            hide = false,
        },
        hideInfoButtons = false,
        escClosesConfig = true,
        showAdvanced = {},
        autoAddPrefs = {
            lastSource = "actionbars",
            selectedBars = { true, true, true, true, true, true },
            showSkipped = false,
            showSources = true,
            sortMode = "source_then_name",
        },
        groups = {
            --[[
                [groupId] = {
                    name = "Group Name",
                    anchor = {
                        point = "CENTER",
                        relativeTo = "UIParent",
                        relativePoint = "CENTER",
                        x = 0,
                        y = 0,
                    },
                    buttons = {
                        [index] = {
                            type = "spell" or "item",
                            id = spellId or itemId,
                            name = "Spell/Item Name",
                        }
                    },
                    style = {
                        buttonSize = 36,
                        buttonSpacing = 2,
                        borderSize = 1,
                        borderColor = {0, 0, 0, 1},
                        backgroundColor = {0, 0, 0, 0.5},
                        orientation = "horizontal", -- "horizontal" or "vertical"
                        buttonsPerRow = 12,
                        showCooldownText = true,
                        cooldownFontSize = 12,
                        cooldownFontOutline = "OUTLINE",
                        cooldownFont = "Friz Quadrata TT",
                        cooldownFontColor = {1, 1, 1, 1},
                        cooldownTextAnchor = "CENTER",
                        cooldownTextXOffset = 0,
                        cooldownTextYOffset = 0,
                        showAuraText = true, -- nil defaults to true via ~= false
                        auraTextFont = "Friz Quadrata TT",
                        auraTextFontSize = 12,
                        auraTextFontOutline = "OUTLINE",
                        auraTextFontColor = {0, 0.925, 1, 1},
                        iconWidthRatio = 1.0, -- 1.0 = square, <1 = taller, >1 = wider
                        maintainAspectRatio = true, -- Prevent icon image stretching
                        showTooltips = true,
                        desaturateOnCooldown = false, -- Desaturate icon while on cooldown
                        showCooldownSwipe = true,
                        cooldownSwipeReverse = false,
                        showCooldownSwipeEdge = true,
                        showGCDSwipe = true, -- Show GCD swipe animation on icons
                        showOutOfRange = false, -- Red-tint icons when target is out of range
                        showAssistedHighlight = false, -- Highlight the assisted combat recommended spell
                        assistedHighlightStyle = "blizzard", -- "blizzard", "solid", or "proc"
                        assistedHighlightColor = {0.3, 1, 0.3, 0.9},
                        assistedHighlightBorderSize = 2,
                        assistedHighlightBlizzardOverhang = 32, -- % overhang for blizzard style
                        assistedHighlightProcOverhang = 32, -- % overhang for proc style
                        assistedHighlightProcColor = {1, 1, 1, 1},
                        showUnusable = true,
                        showLossOfControl = true,
                        procGlowOverhang = 32,
                        procGlowColor = {1, 1, 1, 1},
                        procGlowStyle = "glow",
                        procGlowSize = 32,
                        procGlowThickness = 2,
                        procGlowSpeed = 60,
                        pandemicGlowStyle = "solid",
                        pandemicGlowColor = {1, 0.5, 0, 1},
                        pandemicGlowSize = 2,
                        pandemicGlowThickness = 2,
                        pandemicGlowSpeed = 60,
                        barPandemicColor = {1, 0.5, 0, 1},
                        pandemicBarEffect = "none",
                        pandemicBarEffectColor = {1, 0.5, 0, 1},
                        pandemicBarEffectSize = 2,
                        pandemicBarEffectThickness = 2,
                        pandemicBarEffectSpeed = 60,
                        auraGlowStyle = "pixel",
                        auraGlowColor = {1, 0.84, 0, 0.9},
                        auraGlowSize = 4,
                        auraGlowThickness = 2,
                        auraGlowSpeed = 60,
                        barAuraColor = {0.2, 1.0, 0.2, 1.0},
                        barAuraEffect = "none",
                        barAuraEffectColor = {1, 0.84, 0, 0.9},
                        barAuraEffectSize = 4,
                        barAuraEffectThickness = 2,
                        barAuraEffectSpeed = 60,
                        strataOrder = nil, -- custom layer order (array of 4 keys) or nil for default
                        showKeybindText = false,
                        keybindFont = "Friz Quadrata TT",
                        keybindFontSize = 10,
                        keybindFontOutline = "OUTLINE",
                        keybindFontColor = {1, 1, 1, 1},
                        keybindAnchor = "TOPRIGHT",
                        keybindXOffset = -2,
                        keybindYOffset = -2,
                        showChargeText = true,
                        chargeFont = "Friz Quadrata TT",
                        chargeFontSize = 12,
                        chargeFontOutline = "OUTLINE",
                        chargeFontColor = {1, 1, 1, 1},
                        chargeFontColorMissing = {1, 1, 1, 1},
                        chargeFontColorZero = {1, 1, 1, 1},
                        chargeAnchor = "BOTTOMRIGHT",
                        chargeXOffset = -2,
                        chargeYOffset = 2,
                    },
                    enabled = true,
                    displayMode = "icons",    -- "icons" or "bars"
                    -- Alpha fade system
                    baselineAlpha = 1,        -- alpha when no force conditions met (0-1)
                    forceAlphaInCombat = false,
                    forceAlphaOutOfCombat = false,
                    forceAlphaMounted = false,
                    forceAlphaTargetExists = false,
                    forceAlphaMouseover = false,
                    -- Force-hidden conditions (drive alpha to 0)
                    forceHideInCombat = false,
                    forceHideOutOfCombat = false,
                    forceHideMounted = false,
                    fadeDelay = 1,            -- seconds before fading after mouseover ends
                    fadeInDuration = 0.2,     -- fade-in animation seconds
                    fadeOutDuration = 0.2,    -- fade-out animation seconds
                    -- Load conditions: true = unload group in this context
                    loadConditions = {
                        raid = false,
                        dungeon = false,
                        delve = false,
                        battleground = false,
                        arena = false,
                        openWorld = false,
                        rested = false,
                        petBattle = true,
                    },
                }
            ]]
        },
        nextGroupId = 1,
        folders = {},       -- [folderId] = { name, order, section }
        nextFolderId = 1,
        globalStyle = {
            buttonSize = 36,
            buttonSpacing = 2,
            borderSize = 1,
            borderColor = {0, 0, 0, 1},
            cooldownFontSize = 12,
            cooldownFontOutline = "OUTLINE",
            cooldownFont = "Friz Quadrata TT",
            cooldownFontColor = {1, 1, 1, 1},
            cooldownTextAnchor = "CENTER",
            cooldownTextXOffset = 0,
            cooldownTextYOffset = 0,
            iconWidthRatio = 1.0,
            maintainAspectRatio = true,
            showTooltips = false,
            desaturateOnCooldown = false,
            showCooldownSwipe = true,
            cooldownSwipeReverse = false,
            showCooldownSwipeEdge = true,
            showGCDSwipe = false,
            showOutOfRange = false,
            showAssistedHighlight = false,
            assistedHighlightStyle = "blizzard",
            assistedHighlightColor = {0.3, 1, 0.3, 0.9},
            assistedHighlightBorderSize = 2,
            assistedHighlightBlizzardOverhang = 32,
            assistedHighlightProcOverhang = 32,
            showUnusable = false,
            showLossOfControl = false,
            procGlowOverhang = 32,
            procGlowColor = {1, 1, 1, 1},
            procGlowStyle = "glow",
            procGlowSize = 32,
            procGlowThickness = 2,
            procGlowSpeed = 60,
            pandemicGlowStyle = "solid",
            pandemicGlowColor = {1, 0.5, 0, 1},
            pandemicGlowSize = 2,
            pandemicGlowThickness = 2,
            pandemicGlowSpeed = 60,
            barPandemicColor = {1, 0.5, 0, 1},
            pandemicBarEffect = "none",
            pandemicBarEffectColor = {1, 0.5, 0, 1},
            pandemicBarEffectSize = 2,
            pandemicBarEffectThickness = 2,
            pandemicBarEffectSpeed = 60,
            auraGlowStyle = "pixel",
            auraGlowColor = {1, 0.84, 0, 0.9},
            auraGlowSize = 4,
            auraGlowThickness = 2,
            auraGlowSpeed = 60,
            barAuraColor = {0.2, 1.0, 0.2, 1.0},
            barAuraEffect = "none",
            barAuraEffectColor = {1, 0.84, 0, 0.9},
            barAuraEffectSize = 4,
            barAuraEffectThickness = 2,
            barAuraEffectSpeed = 60,
            assistedHighlightProcColor = {1, 1, 1, 1},
            strataOrder = nil,
            showKeybindText = false,
            keybindFont = "Friz Quadrata TT",
            keybindFontSize = 10,
            keybindFontOutline = "OUTLINE",
            keybindFontColor = {1, 1, 1, 1},
            keybindAnchor = "TOPRIGHT",
            keybindXOffset = -2,
            keybindYOffset = -2,
            showChargeText = true,
            chargeFont = "Friz Quadrata TT",
            chargeFontSize = 12,
            chargeFontOutline = "OUTLINE",
            chargeFontColor = {1, 1, 1, 1},
            chargeFontColorMissing = {1, 1, 1, 1},
            chargeFontColorZero = {1, 1, 1, 1},
            chargeAnchor = "BOTTOMRIGHT",
            chargeXOffset = -2,
            chargeYOffset = 2,
            -- Bar display mode defaults
            barLength = 180,
            barHeight = 20,
            barColor = {0.2, 0.6, 1.0, 1.0},
            barCooldownColor = {0.6, 0.13, 0.18, 1.0},
            barChargeColor = {1.0, 0.82, 0.0, 1.0},
            barBgColor = {0.1, 0.1, 0.1, 0.8},
            showBarIcon = true,
            barIconSizeOverride = false,
            barIconSize = 20,
            showBarNameText = true,
            barNameFont = "Friz Quadrata TT",
            barNameFontSize = 10,
            barNameFontOutline = "OUTLINE",
            barNameFontColor = {1, 1, 1, 1},
            showBarReadyText = false,
            barReadyText = "Ready",
            barReadyTextColor = {0.2, 1.0, 0.2, 1.0},
            barReadyFontSize = 12,
            barReadyFont = "Friz Quadrata TT",
            barReadyFontOutline = "OUTLINE",
            barUpdateInterval = 0.025,  -- seconds between bar fill updates (~40Hz default)
            barTexture = "Solid",
        },
        locked = false,
        cdmHidden = false,
        resourceBars = {
            enabled = true,
            anchorGroupId = nil,
            inheritAlpha = false,
            yOffset = 3,
            barHeight = 12,
            barSpacing = 3.6,
            barTexture = "Solid",
            backgroundColor = { 0, 0, 0, 0.5 },
            borderStyle = "pixel",
            borderColor = { 0, 0, 0, 1 },
            borderSize = 1,
            segmentGap = 4,
            hideManaForNonHealer = true,
            resources = {
                [100] = {
                    enabled = true,
                    mwBaseColor = nil,
                    mwOverlayColor = nil,
                    mwMaxColor = nil,
                },
            },
            customAuraBarSlots = {
                [1] = { position = "below", order = 1001 },
                [2] = { position = "below", order = 1002 },
                [3] = { position = "below", order = 1003 },
            },
            customAuraBars = {},
            textFont = "Friz Quadrata TT",
            textFontSize = 10,
            textFontOutline = "OUTLINE",
            textFontColor = { 1, 1, 1, 1 },
            textFormat = "current",
        },
        castBar = {
            enabled = true,
            stylingEnabled = true,
            anchorGroupId = nil,
            position = "below",
            order = 2000,
            yOffset = 0,
            height = 15,
            barColor = { 1.0, 0.7, 0.0, 1.0 },
            backgroundColor = { 0, 0, 0, 0.5 },
            barTexture = "Solid",
            showIcon = true,
            iconSize = 16,
            iconFlipSide = false,
            iconOffset = false,
            iconOffsetX = 0,
            iconOffsetY = 0,
            iconBorderSize = 1,
            showSpark = true,
            showSparkTrail = true,
            showInterruptShake = true,
            showInterruptGlow = true,
            showCastFinishFX = true,
            borderStyle = "pixel",
            borderColor = { 0, 0, 0, 1 },
            borderSize = 1,
            showNameText = true,
            nameFont = "Friz Quadrata TT",
            nameFontSize = 10,
            nameFontOutline = "OUTLINE",
            nameFontColor = { 1, 1, 1, 1 },
            showCastTimeText = true,
            castTimeFont = "Friz Quadrata TT",
            castTimeFontSize = 10,
            castTimeFontOutline = "OUTLINE",
            castTimeFontColor = { 1, 1, 1, 1 },
            castTimeXOffset = 0,
            castTimeYOffset = 0,
        },
        frameAnchoring = {
            enabled = false,
            anchorGroupId = nil,
            mirroring = true,
            inheritAlpha = false,
            unitFrameAddon = nil,
            customPlayerFrame = "",
            customTargetFrame = "",
            player = {
                anchorPoint = "RIGHT",
                relativePoint = "LEFT",
                xOffset = -10,
                yOffset = 0,
            },
            target = {
                anchorPoint = "LEFT",
                relativePoint = "RIGHT",
                xOffset = 10,
                yOffset = 0,
            },
        },
    },
}

ST._defaults = defaults

------------------------------------------------------------------------
-- OVERRIDE SECTIONS REGISTRY
-- Maps section IDs to their labels, style keys, and applicable display modes.
-- Used by promote/revert logic and UI builders.
------------------------------------------------------------------------
ST.OVERRIDE_SECTIONS = {
    -- Icon Mode — Appearance Tab
    borderSettings = {
        label = "Border",
        keys = {"borderSize", "borderColor"},
        modes = {icons = true, bars = true},
    },
    backgroundColor = {
        label = "Background Color",
        keys = {"backgroundColor"},
        modes = {icons = true},
    },
    cooldownText = {
        label = "Cooldown Text",
        keys = {"showCooldownText", "cooldownFont", "cooldownFontSize", "cooldownFontOutline", "cooldownFontColor", "cooldownTextAnchor", "cooldownTextXOffset", "cooldownTextYOffset"},
        modes = {icons = true, bars = true},
    },
    auraText = {
        label = "Aura Duration Text",
        keys = {"showAuraText", "auraTextFont", "auraTextFontSize", "auraTextFontOutline", "auraTextFontColor"},
        modes = {icons = true, bars = true},
    },
    auraStackText = {
        label = "Aura Stack Text",
        keys = {"showAuraStackText", "auraStackFont", "auraStackFontSize", "auraStackFontOutline", "auraStackFontColor", "auraStackAnchor", "auraStackXOffset", "auraStackYOffset"},
        modes = {icons = true, bars = true},
    },
    keybindText = {
        label = "Keybind Text",
        keys = {"showKeybindText", "keybindFont", "keybindFontSize", "keybindFontOutline", "keybindFontColor", "keybindAnchor", "keybindXOffset", "keybindYOffset"},
        modes = {icons = true},
    },
    chargeText = {
        label = "Charge Text",
        keys = {"showChargeText", "chargeFont", "chargeFontSize", "chargeFontOutline", "chargeFontColor", "chargeFontColorMissing", "chargeFontColorZero", "chargeAnchor", "chargeXOffset", "chargeYOffset"},
        modes = {icons = true, bars = true},
    },
    -- Icon Mode — Extras Tab
    desaturation = {
        label = "Desaturation",
        keys = {"desaturateOnCooldown"},
        modes = {icons = true, bars = true},
    },
    cooldownSwipe = {
        label = "Cooldown Swipe",
        keys = {"showCooldownSwipe", "cooldownSwipeReverse", "showCooldownSwipeEdge"},
        modes = {icons = true},
    },
    showGCDSwipe = {
        label = "Show GCD Swipe",
        keys = {"showGCDSwipe"},
        modes = {icons = true, bars = true},
    },
    showOutOfRange = {
        label = "Show Out of Range",
        keys = {"showOutOfRange"},
        modes = {icons = true},
    },
    showTooltips = {
        label = "Show Tooltips",
        keys = {"showTooltips"},
        modes = {icons = true, bars = true},
    },
    lossOfControl = {
        label = "Loss of Control",
        keys = {"showLossOfControl"},
        modes = {icons = true, bars = true},
    },
    unusableDimming = {
        label = "Unusable Dimming",
        keys = {"showUnusable"},
        modes = {icons = true, bars = true},
    },
    assistedHighlight = {
        label = "Assisted Highlight",
        keys = {"showAssistedHighlight", "assistedHighlightStyle", "assistedHighlightColor", "assistedHighlightBorderSize", "assistedHighlightBlizzardOverhang", "assistedHighlightProcOverhang", "assistedHighlightProcColor"},
        modes = {icons = true},
    },
    procGlow = {
        label = "Proc Glow",
        keys = {"procGlowStyle", "procGlowColor", "procGlowSize", "procGlowThickness", "procGlowSpeed"},
        modes = {icons = true},
    },
    pandemicGlow = {
        label = "Pandemic Glow",
        keys = {"pandemicGlowStyle", "pandemicGlowColor", "pandemicGlowSize", "pandemicGlowThickness", "pandemicGlowSpeed"},
        modes = {icons = true},
    },
    auraIndicator = {
        label = "Active Aura Glow",
        keys = {"auraGlowStyle", "auraGlowColor", "auraGlowSize", "auraGlowThickness", "auraGlowSpeed"},
        modes = {icons = true},
    },
    -- Bar Mode — Appearance Tab
    pandemicBar = {
        label = "Pandemic Indicator",
        keys = {"barPandemicColor", "pandemicBarEffect", "pandemicBarEffectColor", "pandemicBarEffectSize", "pandemicBarEffectThickness", "pandemicBarEffectSpeed"},
        modes = {bars = true},
    },
    barActiveAura = {
        label = "Active Aura Indicator",
        keys = {"barAuraColor", "barAuraEffect", "barAuraEffectColor", "barAuraEffectSize", "barAuraEffectThickness", "barAuraEffectSpeed"},
        modes = {bars = true},
    },
    barIcon = {
        label = "Bar Icon",
        keys = {"showBarIcon", "barIconReverse", "barIconOffset", "barIconSizeOverride", "barIconSize"},
        modes = {bars = true},
    },
    barColors = {
        label = "Bar Colors",
        keys = {"barColor", "barCooldownColor", "barChargeColor", "barBgColor"},
        modes = {bars = true},
    },
    barNameText = {
        label = "Name Text",
        keys = {"showBarNameText", "barNameTextReverse", "barNameFont", "barNameFontSize", "barNameFontOutline", "barNameFontColor"},
        modes = {bars = true},
    },
    barReadyText = {
        label = "Ready Text",
        keys = {"showBarReadyText", "barReadyText", "barReadyTextColor", "barReadyFontSize", "barReadyFont", "barReadyFontOutline"},
        modes = {bars = true},
    },
}
